### ISSUE TITLE
Mixed usage of ORDERLABEL / LABEL on newspaper export

### ISSUE THREAD

**Issue by henning-gerhardt** [goobi/goobi-production#286]
On exporting a newspaper the usage of ``ORDERLABEL`` and ``LABEL`` inside logical structmap is mixed. For year ``LABEL`` is used and for month and day ``ORDERLABEL``.

```xml
  <mets:structMap TYPE="LOGICAL">
    <mets:div CONTENTIDS="http://digital.slub-dresden.de/id391878840" ID="LOG_0007" LABEL="Leipziger jüdische Wochenschau" ORDERLABEL="Leipziger jüdische Wochenschau" TYPE="newspaper">
      <mets:mptr xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="http://digital.slub-dresden.de/fileadmin/data/391878840/391878840_anchor.xml"/>
      <mets:div ADMID="AMD" ID="LOG_0008" LABEL="1930" TYPE="year">
        <mets:mptr xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="http://digital.slub-dresden.de/fileadmin/data/391878840/391878840_year.xml"/>
        <mets:div ADMID="AMD" ID="LOG_0009" ORDERLABEL="1" TYPE="month">
          <mets:div ADMID="AMD" ID="LOG_0010" ORDERLABEL="17" TYPE="day">
            <mets:div ADMID="AMD" DMDID="DMDLOG_0004" ID="LOG_0011" TYPE="issue"/>
          </mets:div>
        </mets:div>
      </mets:div>
    </mets:div>
  </mets:structMap>
```

Is it possible to change this to

- both ``ORDERLABEL`` and ``LABEL``
- only ``ORDERLABEL``
- only ``LABEL``

? First solution would be best solution.

**Comment by sebastian-meyer** [comment]
This is 1 of only 3 remaining issues with milestone 1.11.
@matthias-ronge could you please have a look at the supposed bug? Adding `TitleDocMainShort` to `year` isn't sufficient to get an `ORDERLABEL` attribute.

**Comment by matthias-ronge** [comment]
Which of the both attributes is the one that is required at `year` level for the calendar in Presentation to work, and wihch one is optional?

**Comment by sebastian-meyer** [comment]
`LABEL` is required on `year` level while `ORDERLABEL` is optional. On `month` and `day` level it's the other way round.

Thanks for the pull request! We'll look into it.

**Comment by matthias-ronge** [comment]
This is how it is implemented now. If the required metadata field is missing, no export will be performed and an exception shall be shown. If the optional field is missing, it should be skipped silently.

**Comment by henning-gerhardt** [comment]
Its only fixed for main meta file (mets.xml). 

For interim anchor file (_year.xml) top (main anchor file) and lowest (meta.xml) reference are ``ORDERLABEL`` / ``LABEL`` missing. 

For main anchor file (_anchor.xml) reference to interim anchor file (_year) ``ORDERLABEL`` / ``LABEL`` are missing.

**Comment by matthias-ronge** [comment]
Should be working now, please verify.

**Comment by matthias-ronge** [comment]
Fixed in UGH: https://github.com/goobi/goobi-ugh/pull/20
