### ISSUE TITLE
db_migrate_1.8_1.10.sql and correction/solution messages

### ISSUE THREAD

**Issue by frank-ulrich-weber** [goobi/goobi-production#287]
db_migrate_1.8_1.10.sql moves all data from table schritteeigenschaften to prozesseeigenschaften. That leads to the situtation that in 1.11 (I think in 1.10.x, too) the text of existing correction/solution messages disappears. 1.11 creates new messages in schritteeigenschaften, too. Keeping existing messages in schritteeigenschaften solves the problem. 

https://github.com/goobi/goobi-contrib/blob/master/db/db_migrate_1.8_1.10.sql

**Comment by henning-gerhardt** [comment]
In my humble opinion the best way is to continue the way of removing class and bean ``schritteeigenschaften``. Old correction/solution messages are not lost only visible on different place. So I started a [possible solution](https://github.com/henning-gerhardt/goobi-production/tree/issue287). Maybe is this a solution for you @frank-ulrich-weber ?

Maybe there is a way to add old correction/solution messages in correct order to process ``wikifield`` through an external script.

**Comment by sebastian-meyer** [comment]
This is 1 of only 3 remaining issues with milestone 1.11.
@frank-ulrich-weber could you please have a look at the proposed changes and confirm them?
