### ISSUE TITLE
Invalid file URIs 

### ISSUE THREAD

**Issue by matthias-ronge** [goobi/goobi-production#293]
On Windows machines, malformed `file:/X:/…` URIs appear in Goobi. The source of this needs to be located and fixed. The correct syntax is: `file:///X:/…` (*three* slashes) (see [Wikipedia](https://en.wikipedia.org/wiki/File_URI_scheme#Windows_2)). See also https://github.com/goobi/goobi-production/issues/289#issuecomment-67621156

**Comment by henning-gerhardt** [comment]
@matthias-ronge : Can this issue closed?

**Comment by henning-gerhardt** [comment]
Never mind: read reference to #289 as merged fix.

**Comment by matthias-ronge** [comment]
It seems to be a Java thing to generally use the malformed file urls on Windows internally, but it does not seem to harm the funtctionality.
