### ISSUE TITLE
Mets Pointer Path not split on automatic export

### ISSUE THREAD

**Issue by henning-gerhardt** [goobi/goobi-production#298]
Affected version: 1.11.x

When using automatic export feature of Goobi to export a multi volume / periodical / newspaper process or any process with any kind of anchor file resulting mets file contains a wrong METS pointer path to its anchor file(s).

METS pointer path is defined as

```
http://digital.slub-dresden.de/fileadmin/data/$(meta.CatalogIDDigital)/$(meta.CatalogIDDigital)_anchor.xml¦http://digital.slub-dresden.de/fileadmin/data/$(meta.CatalogIDDigital)/$(meta.CatalogIDDigital)_year.xml
```

inside project properties. The resulting mets file of an automatic export contains following wrong METS pointer path reference

```xml
<mets:mptr xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="http://digital.slub-dresden.de/fileadmin/data/403804620-19490000/403804620-19490000_anchor.xml¦http://digital.slub-dresden.de/fileadmin/data/403804620-19490000/403804620-19490000_year.xml"/> 
```

Correct should be

```xml
<mets:mptr xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="http://digital.slub-dresden.de/fileadmin/data/403804620-19490000/403804620-19490000_anchor.xml"/>
```

Using other Goobi export mechanism (DMS button, Goobi script or non automatic exports) are not affected.

**Comment by henning-gerhardt** [comment]
After some investigations I found in class [ExportMets.java](https://github.com/goobi/goobi-production/blob/1.11.x/Goobi/src/de/sub/goobi/export/download/ExportMetsWithoutHibernate.java#L287-289) handling of mets pointer anchor separator. But on automatic export class [ExportMetsWithoutHibernate](https://github.com/goobi/goobi-production/blob/1.11.x/Goobi/src/de/sub/goobi/export/download/ExportMetsWithoutHibernate.java#L287-289) is used and there is handling missing.

**Comment by sebastian-meyer** [comment]
@matthias-ronge could you please look into this? It seems to being introduced with the recent newspaper additions.

**Comment by henning-gerhardt** [comment]
Tested with different document types and export mechanism (manual, button, automatic). Works for me.
