### ISSUE TITLE
Could not copy process id to multiple day issues

### ISSUE THREAD

**Issue by henning-gerhardt** [goobi/goobi-production#303]
We tried to switch from a daily newspaper issue to a monthly newspaper issue and changed working export copy rule

```
/NewspaperYear[0]/NewspaperMonth[0]/NewspaperDay[0]/PeriodicalIssue@ProcessID ""\= $process.id;
```

to

```
/NewspaperYear[0]/NewspaperMonth[0]/NewspaperDay[*]/PeriodicalIssue@ProcessID ""\= $process.id
```

to get process id to every periodical issue.

On export we got following error message inside task manager for this process:

```
Could not resolve metadata path: In this regard, index "*" is not allowed.
```

Our other changed export copy rule

```
/NewspaperYear[0]/NewspaperMonth[0]/NewspaperDay[*]/PeriodicalIssue@PublicationDate \=format "%1$04d-%2$02d-%3$02d" #1@TitleDocMain #2@TitleDocMainShort #@TitleDocMainShort;
```

works perfect.

**Comment by henning-gerhardt** [comment]
To clarify: procces id is only a sample. We copying more information to PeriodicalIssue like singleDigCollection.

**Comment by matthias-ronge** [comment]
The `""=` operator does only create the metadatum at the structural element on the left hand side if there isn’t such a metadatum yet. Therefore it has to check the left hand side first for this condition, so it needs to know which element to check against. If you don’t need condition checking, this might do what you want:
```
/NewspaperYear[0]/NewspaperMonth[0]/NewspaperDay[*]/PeriodicalIssue@PublicationDate \=format "%s" $process.id;
```
If condition checking in required, you will need to create an individual rule for each path.

**Comment by henning-gerhardt** [comment]
Ok, thank you. 

If I try it I got only error message

``Too many arguments in line: /NewspaperYear[0]/NewspaperMonth[0]/NewspaperDay[*]/PeriodicalIssue@ProcessID = format "%s" $process.id``

The ``copyData.onExport`` rule contains only

``copyData.onExport=/NewspaperYear[0]/NewspaperMonth[0]/NewspaperDay[*]/PeriodicalIssue@ProcessID \= format "%s" $process.id``

``ProcessID`` is an allowed metadata field for ``PeriodicalIssue``.

**Comment by matthias-ronge** [comment]
You have a spurious space in your operator. The operator is `=format`, so please change
```
…PeriodicalIssue@ProcessID \= format "%s" $process.id
```
to
```
…PeriodicalIssue@ProcessID \=format "%s" $process.id
```

**Comment by henning-gerhardt** [comment]
Thank you. Its works now for me.
