### ISSUE TITLE
Asynchronous DMS export cannot initialize Regelsatz from Hibernate

### ISSUE THREAD

**Issue by matthias-ronge** [goobi/goobi-production#313]
Typical exceptions read `HibernateException: proxy handle is no longer valid` or `LazyInitializationException: could not initialize proxy - no Session`.

Hibernated `de.sub.goobi.beans.Regelsatz` object must be initialized synchronously during task creation.

**Comment by henning-gerhardt** [comment]
It this kind of error similar to following error message

``org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: de.sub.goobi.beans.Prozess.schritte, no session or session was closed`` 

?

**Comment by henning-gerhardt** [comment]
Ignore my comment. This ``LazyInitializationException`` has something to do with statistic information. Final Goobi source access was in

```de.sub.goobi.beans.Prozess.getFortschritt3(Prozess.java:942)```
