### ISSUE TITLE
Calendar editor crashes if blocks in XML file overlap

### ISSUE THREAD

**Issue by matthias-ronge** [goobi/goobi-production#362]
**Error:** Uploading a course of appearance with overlapping date ranges of blocks causes the calendar editor to crash and show a stack trace. Example:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<course><processes><process>
    <title index="A block">
        <appeared issue="Daily issue" date="1975-01-02"/>
        <appeared issue="Daily issue" date="1975-01-04"/>
    </title>
    <title index="Another block">
        <appeared issue="Daily issue" date="1975-01-03"/>
    </title>
</process></processes></course>
```

**Goal:** A helpful error message should be shown.

**Expericenced with browser:** Internet Explorer in Eclipse

**Comment by henning-gerhardt** [comment]
@matthias-ronge : Can this issue be closed?

**Comment by matthias-ronge** [comment]
Pull request successfully merged and closed.
