### ISSUE TITLE
Metadata editor refuses saving with empty MetsPointerURL

### ISSUE THREAD

**Issue by matthias-ronge** [goobi/goobi-production#369]
The metadata editor refuses saving if a tree node has an empty field `MetsPointerURL`. This may happen if the metadata field `MetsPointerURL` is set `DefaultDisplay="true"` in the ruleset. [DocStruct.getAllRealSuccessors()](https://github.com/goobi/goobi-ugh/blob/master/ugh/src/ugh/dl/DocStruct.java#L340) should be changed to treat a present, empty field equal to an absent one.

Prerequisite is a desicion if pull request #357 will be merged or rejected.

**Comment by henning-gerhardt** [comment]
Pull request #357 need some time as logn this project is licensed GPL2+ and UGH is licensed LGPL3+. First update license to GPL3+ and then merge UGH back to this project.

Make the necessary fixes in UGH. Team mate found an issue belong xml namespace prefixes (premis and mix) and there is at least on other issue more.

**Comment by stweil** [comment]
@henning-gerhardt, the pull request #357 does not depend on the license question: we already use UGH in its binary form, so there is already a license issue which only has two possible solutions. One of them (removing UGH) is not really a solution. Pull request #361 would be a first step in the right direction.

IMHO pull request #357 needs more discussion before being applied. I still think that a git submodule would be the better solution.

**Comment by henning-gerhardt** [comment]
- Pull request #361 is on hold until a non-warranty clause paragraph is added to license text and approved by management and lawyer.
- My misgivings to git submodule usage are explained in German inside comments of pull request #357.

**Comment by matthias-ronge** [comment]
Moved to goobi-ugh project:
https://github.com/goobi/goobi-ugh/issues/25
