### ISSUE TITLE
Double page pagination

### ISSUE THREAD

**Issue by matthias-ronge** [goobi/goobi-production#378]
Goobi Production shall be extended to provide the option of a double page pagination. In this mode, a physical scan contains two pages, left and right, with one page number each. Example:

    13: 4;5
    14: 6;7
    15: 8;9

The double page pagination shall support all available pagination types:

 * arabic, roman, uncounted
 * fictious pagination
 * selected pages only / start from selected page

It is possible to define the separator character used (`;` in the example above). Disallowed characters are to be rejected.

The development of this feature is funded by Gottfried-Wilhelm Leibnitz Bibliothek Hannover.

**Comment by stweil** [comment]
UB Mannheim has also newspapers scanned with double pages. We thought of cutting the pages into left and right pages by software, but maybe your approach is better.

Are there also plans how to handle those double pages in Goobi.Presentation / DFG viewer?

**Comment by sebastian-meyer** [comment]
This feature would lead to non-standard METS files as the DFG document model requires a page-centered encoding (see "DFG Praxisregeln zur Digitalisierung" or the METS application profile for the DFG Viewer). This would impact some features of Goobi.Presentation, too.

**Comment by henning-gerhardt** [comment]
Pull-Request #381 for this issue is merged.
