### ISSUE TITLE
SafeFile is missing toString() method

### ISSUE THREAD

**Issue by matthias-ronge** [goobi/goobi-production#414]
This causes nonsense paths to be composed, such as `org.goobi.io.SafeFile@1234567/filename.ext` and so breaks export.

Fix: to add toString() method for delegate object

**Comment by stweil** [comment]
Can we be sure that this is the only missing method?

**Comment by matthias-ronge** [comment]
Missing methods would be reported by the compiler. Here it was not explicitly missing, but inherited from `Object.toString()`, which does not print the file path but some string which was not useful.

**Comment by stweil** [comment]
Yes, and other methods inherited from Object might show wrong results like toString...

**Comment by matthias-ronge** [comment]
There is at least no explicit call to neither `clone()`, `equals()`, `finalize()`, nor `hashCode()` from the code, where there *are* calls to `toString()`. There are some calls to `equals()` on an `Object` not further specified, but since they compare to something that isn’t a `SafeFile` at all a comparison would cause to return `false` in any way.

@henning-gerhardt what do you think?

**Comment by henning-gerhardt** [comment]
For reported issue this pull-request should be ok to fix `toString()` method call. If any other methods must be implemented should be discussed in an other issue and fixed in an other pull request if needed.
