### ISSUE TITLE
`ant test` fails on newer Linux distributions

### ISSUE THREAD

**Issue by stweil** [goobi/goobi-production#425]
`ant test` fails on Travis and also on Debian Stretch, maybe caused by a newer versions of `ant`.
Here is the output on Debian GNU Linux (Stretch = testing):

    Buildfile: /home/stefan/src/github/stweil/goobi-production/build.xml

    check-java-version:

    check-classpath:

    check-servlet-api:

    check-jsp-compilation:

    check-preconditions:

    createDirs:
       [delete] Deleting directory /home/stefan/src/github/stweil/goobi-production/build/javadoc
        [mkdir] Created dir: /home/stefan/src/github/stweil/goobi-production/build/javadoc
       [delete] Deleting directory /home/stefan/src/github/stweil/goobi-production/build/test-reports
        [mkdir] Created dir: /home/stefan/src/github/stweil/goobi-production/build/test-reports

    init:

    copy-hibernate-resources:

    compile-jsp:

    compile:

    compile-tests:
        [javac] Compiling 2 source files to /home/stefan/src/github/stweil/goobi-production/build/test-classes
        [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.5
        [javac] 1 warning

    junit:
    CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/WEB-INF/faces-config.xml is not a JAR.
        [junit] CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/WEB-INF/faces-config.xml is not a JAR.
    CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/WEB-INF/metadata-editor-config.xml is not a JAR.
        [junit] CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/WEB-INF/metadata-editor-config.xml is not a JAR.
    CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/WEB-INF/reverse-proxy.xml is not a JAR.
        [junit] CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/WEB-INF/reverse-proxy.xml is not a JAR.
    CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/WEB-INF/web.xml is not a JAR.
        [junit] CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/WEB-INF/web.xml is not a JAR.
    CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/config/c3p0.properties is not a JAR.
        [junit] CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/config/c3p0.properties is not a JAR.
    CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/config/contentServerConfig.xml is not a JAR.
        [junit] CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/config/contentServerConfig.xml is not a JAR.
    CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/config/docket.xsl is not a JAR.
        [junit] CLASSPATH element /home/stefan/src/github/stweil/goobi-production/Goobi/config/docket.xsl is not a JAR.

**Comment by henning-gerhardt** [comment]
Which java and ant version did you use to build and running tests? I can't reproduce this on my development system.

**Comment by stweil** [comment]
I ran `ant -lib /usr/share/java/tomcat8-servlet-api-8.0.30.jar test` with this environment:

    java version "1.7.0_91"
    OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1)
    OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

    Apache Ant(TM) version 1.9.6 compiled on July 6 2015

**Comment by henning-gerhardt** [comment]
I updated java to your version (my was on hold and old). I can reproduce your error if I commented out `tomcat.dir.lib` in `build.properties` and run tests through `ant -lib /usr/share/tomcat7/lib test`.

Running tests results in this failure but not build the war file.

**Comment by henning-gerhardt** [comment]
Some notes
- only `junit` class path is affected
- if `tomcat.dir.lib` is not defined through `build.properties`, value of this variable is [current directory](https://github.com/goobi/goobi-production/blob/master/build.xml#L53)

**Comment by stweil** [comment]
Indeed, removing all lines with `tomcat.dir.lib` from `build.xml` fixed the problem as well. If we keep `tomcat.dir.lib`, at least the default value should be changed to something that works.

**Comment by henning-gerhardt** [comment]
Can you try my changes in https://github.com/henning-gerhardt/goobi-production/tree/issue_425 (or commit https://github.com/henning-gerhardt/goobi-production/commit/2c76bc46b76dfb029dfedfe6554c6dd260cd07fb)?

**Comment by stweil** [comment]
It fails when `CATALINA_HOME` is unset:

    goobi-production/build.xml:146: goobi-production/${env.CATALINA_HOME}/lib does not exist.

**Comment by henning-gerhardt** [comment]
See my edit: need some love as is it a fast and dirty solution.

**Comment by henning-gerhardt** [comment]
Could this issues closed?

**Comment by stweil** [comment]
Yes, pull request #426 fixed this, so you may close this issue. Thanks.

**Comment by henning-gerhardt** [comment]
Closed.
